on: [push]

name: VM

jobs:

    deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
         node-version: '14'
      
      - run: npm install
      - run: npm test
